# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Pay-As-You-Go (59ed7061-63b2-4299-bd5a-f81e3e98d46e)'
    appName: 'testapp001'
    package: $(System.DefaultWorkingDirectory)/**/*.zip
